name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Linter configuration
        linters: "eslint,stylelint"
        eslint: true
        eslint_config_file: ".eslintrc.json"
        eslint_extra_args: "--no-eslintrc"
        # Stylelint configuration (if needed)
        stylelint: true
        stylelint_config_file: ".stylelintrc.json" # Optional
